/**
 * Run following code in https://developers.weixin.qq.com/miniprogram/dev/component/
 *
 * copy($$('tbody td:first-child').map(i => i.innerText.trim()).slice(0, -3))
 */

module.exports = [
  "template",
  "slot",
  "block",
  "include"
].concat([
  "movable-view",
  "cover-image",
  "cover-view",
  "movable-area",
  "scroll-view",
  "swiper",
  "swiper-item",
  "view",
  "icon",
  "progress",
  "rich-text",
  "text",
  "button",
  "checkbox",
  "checkbox-group",
  "editor",
  "form",
  "input",
  "label",
  "picker",
  "picker-view",
  "picker-view-column",
  "radio",
  "radio-group",
  "slider",
  "switch",
  "textarea",
  "functional-page-navigator",
  "navigator",
  "audio",
  "camera",
  "image",
  "live-player",
  "live-pusher",
  "video",
  "map",
  "canvas",
  "web-view",
  "ad",
  "official-account",
  "open-data"
])
